In [2]:
import numpy as np

In [61]:
n_e=3
n_m=4
matrice=np.random.randint(50,100,size=(n_e,n_m))
#matrice=np.random.random(size=(n_e,n_m))*20
print(matrice)
notetotale=matrice.sum(axis=1)#1 pour la ligne
notemoyenne=matrice.mean(axis=1)
#print(np.expand_dims(notetotale, 0).T)#pour transposer la matrice
pourcentage=(notetotale/n_matiere)
print(np.expand_dims(pourcentage, -1))
grades=np.zeros_like(pourcentage,dtype=object)
grades[pourcentage>90]="A+"
grades[(pourcentage>80) & (grades == 0)]="A"
grades[(pourcentage>70) & (grades == 0)]="B+"
grades[(pourcentage>60) & (grades == 0)]="B"
grades[(pourcentage>50) & (grades == 0)]="C"
grades[(pourcentage<50) & (grades == 0)]="F"
print(grades)



[[95 67 91 54]
 [64 56 65 95]
 [79 90 66 89]]
[[76.75]
 [70.  ]
 [81.  ]]
['B+' 'B' 'A']
